project_name: "example_node"
# target_dir: "../Generated_Project"
# resources_rel_path: "../resources"

# ------------------------------------------------------------------------------
# MCU Selection
# The generator will use 'part_number' to find:
#   1. Startup file: startup_{part_number lower}.s
#   2. Linker script: {part_number}_FLASH.ld
# ------------------------------------------------------------------------------
mcu:
  family: STM32H5xx
  part_number: STM32H563xx 
  
# ------------------------------------------------------------------------------
# Clock Tree Configuration
# Define Inputs (Crystals/RC) and Outputs (Target Hz).
# The Generator will calculate the Prescalers/Dividers (M, N, P, Q, R) automatically.
# ------------------------------------------------------------------------------
clock_config:
  # 1. Input Sources (Original Frequencies)
  sources:
    hsi:
      enable: true
      frequency: 64000000   # Internal RC (Default 64MHz on STM32H5)
    
    hse:
      enable: true         # Set to 'true' if using external crystal
      frequency: 8000000   # Your Crystal Value (e.g. 25MHz)
      bypass: true         # 'true' for clock generator, 'false' for crystal

  # 2. PLL Configurations (Target Frequencies after Conversion)
  # The solver will try to match these targets as closely as possible.
  pll1:
    enable: true
    source: HSI             # Input Source: HSI or HSE
    targets:
      p: 250000000          # System Clock: 250 MHz
      q: 0          # PLL1_Q: 500 MHz
      r: 0          # PLL1_R: 500 MHz

  # Optional: PLL2 for Peripherals (FDCAN, UART, etc.)
  # Defined similarly if needed, otherwise 'enable: false'
  pll2:
    enable: true
    source: HSE
    targets:
      p: 0                  # 0 = Unused/Don't Care
      q: 20000000           # Example: 20 MHz for FDCAN
      r: 0

  # ----------------------------------------------------------------------------
  # Bus Clock Configuration
  # Maps to RCC_ClkInitTypeDef
  # ----------------------------------------------------------------------------
  buses:
    sysclk_source: pllclk   # Selects the System Clock Source (HSI, HSE, PLLCLK)
    
    # AHB Divider: Divides SYSCLK to get HCLK (Core Clock)
    # Valid: 1, 2, 4, 8, 16, 64, 128, 256, 512
    ahb_div: 1              
    
    # APB Dividers: Divide HCLK to get Peripheral Clocks (PCLKx)
    # Valid: 1, 2, 4, 8, 16
    apb1_div: 1             # PCLK1 (Low speed peripherals)
    apb2_div: 1             # PCLK2 (High speed peripherals)
    apb3_div: 1             # PCLK3

# ------------------------------------------------------------------------------
# Peripheral Modules
# - Keys (fdcan1, usart2) must match the Hardware Instance name.
# - 'clock_source' maps to the HAL RCC definitions (e.g., PLL2Q, PLL2R, PCLK1).
# ------------------------------------------------------------------------------
modules:

  # --- FDCAN GROUP ---
  fdcan:
    enable: true
    clock_source: pll2q
    instances:
      fdcan1:
        enable: true
        speed: 500000         # Target Bitrate: 500 kBit/s
        pins:
          rx: A11
          tx: A12
        interrupts:
          it0: { priority: 5, subpriority: 0 }
        
        # Types: RANGE, DUAL, MASK
        # Configs: TO_RXFIFO0, TO_RXFIFO1, REJECT, RXFIFO0_HP, RXFIFO1_HP
        filters:
          - type: global
            action: fifo0
          - type: range
            action: fifo0
            id1: 0x100
            id2: 0x110
          - type: mask
            action: fifo1
            id1: 0x200       # ID
            id2: 0x7F0       # Mask

      fdcan2:
        enable: true
        speed: 1000000
        pins:
          rx: B12
          tx: B13
        interrupts:
          it0: { priority: 5, subpriority: 0 }
        
        filters:
          - type: dual
            action: fifo0_hp # High Priority
            id1: 0x010         # Emergency Message
            id2: 0x020         # Critical Control

  # --- USART GROUP ---
  usart:
    enable: true
    clock_source: pll2q
    instances:
      usart1:
        enable: true
        speed: 115200         # Baudrate
        pins:
          rx: A10
          tx: A9
        interrupts:
          global: { priority: 6, subpriority: 0 }

      usart3:
        enable: false
        speed: 9600
        pins:
          rx: D9
          tx: D8
        interrupts:
          global: { priority: 7, subpriority: 0 }
