#include "main.h"

#include "FreeRTOS.h"
#include "task.h"

#include "can.hpp"
#include "gpio.hpp"
#include "serial.hpp"
#include "timer.hpp"
#include "raceup_setup.h"

void app_start(void);

int main(void)
{
  HAL_Init();

  // Call the functions generated by our Python/Jinja script
  SystemClock_Config();
  config_FDCAN();
  config_GPIO();

  (void)ru::driver::Driver::start();
  (void)ru::driver::Can::start();
  (void)ru::driver::Gpio::start();
  (void)ru::driver::Serial::start();
  (void)ru::driver::Timer::start();

  app_start();

  vTaskStartScheduler();
  while (1)
  {
  }
}

// Keep the error handler and asserts, but delete the old SystemClock_Config, config_FDCAN, and config_LED
void Error_Handler(void)
{
  __disable_irq();
  while (1) {
  }
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
}
#endif /* USE_FULL_ASSERT */
